# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: api-db-svc
# #   labels:
# #     app: api-db
# #   namespace: banksim
# # spec:
# #   ports:
# #     - port: 5432
# #   selector:
# #     app: api-db
# #     tier: backend
# #   #type: ClusterIP
# #   clusterIP: None 
## ---
# # apiVersion: apps/v1
# # kind: Deployment
# # metadata:
# #   name: api-db
# #   labels:
# #     app: api-db
# #   namespace: banksim
# # spec:
# #   selector:
# #     matchLabels:
# #       app: api-db
# #       tier: backend
# #   strategy:
# #     type: Recreate
# #   template:
# #     metadata:
# #       labels:
# #         app: api-db
# #         tier: backend
# #       namespace: banksim
# #     spec:
# #       containers:
# #       - image: postgres
# #         name: cnse-api-db
# #         env:
# #         - name: POSTGRES_PASSWORD
# #           value: pass1234
# #         - name: POSTGRES_DB
# #           value: "banksim"
# #         - name: POSTGRES_USER
# #           value: "apiuser"
# #         ports:
# #         - containerPort: 5432
# #           name: psql-db
# #         volumeMounts:
# #         - name: db-persistent-storage
# #           mountPath: /var/lib/postgresql/data
# #       volumes:
# #       - name: db-persistent-storage
# #         persistentVolumeClaim:
# #           claimName: db-pv-claim


# apiVersion: v1
# kind: Service
# metadata:
#   name: api-db-svc
#   labels:
#     app: api-db
#   namespace: cnse
# spec:
#   ports:
#     - port: 5432
#   selector:
#     app: api-db
#     tier: backend
#   #type: ClusterIP
#   clusterIP: None 
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: api-db
#   labels:
#     app: api-db
#   namespace: cnse
# spec:
#   selector:
#     matchLabels:
#       app: api-db
#       tier: backend
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: api-db
#         tier: backend
#       namespace: cnse
#     spec:
#       containers:
#       - image: postgres:13.3
#         name: cnse-api-db
#         env:
#         - name: POSTGRES_PASSWORD
#           value: pass1234
#         - name: POSTGRES_DB
#           value: "banksim"
#         - name: POSTGRES_USER
#           value: "apiuser"
#         ports:
#         - containerPort: 5432
#           name: api-db
#         volumeMounts:
#         - name: db-persistent-storage
#           mountPath: /var/lib/postgresql/data
#         resources:
#             limits:
#               cpu: '500m'
#               memory: '100Mi'
#       volumes:
#       - name: db-persistent-storage
#         persistentVolumeClaim:
#           claimName: db-pvc

apiVersion: v1
kind: Service
metadata:
  name: api-db-svc
  labels:
    app: api-db
  namespace: banksim
spec:
  ports:
    - port: 5432
  selector:
    app: api-db
    tier: backend
  #type: ClusterIP
  clusterIP: None 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-db
  labels:
    app: api-db
  namespace: banksim
spec:
  selector:
    matchLabels:
      app: api-db
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api-db
        tier: backend
      namespace: banksim
    spec:
      containers:
      - image: postgres:13.3
        name: cnse-api-db
        env:
        - name: POSTGRES_PASSWORD
          value: pass1234
        - name: POSTGRES_DB
          value: "banksim"
        - name: POSTGRES_USER
          value: "apiuser"
        ports:
        - containerPort: 5432
          name: api-db
        volumeMounts:
        - name: db-persistent-storage
          mountPath: /var/lib/postgresql/data
        resources:
            limits:
              cpu: '500m'
              memory: '100Mi'
      volumes:
      - name: db-persistent-storage
        persistentVolumeClaim:
          claimName: db-pvc